package add;

public enum MessageType {
    ALREADY_ONLINE, NOT_ONLINE, CHAT, DATABASE, NORMAL, NEW_USER, USER_LEFT,
    SELECTED_SESSION, NEW_SESSION, ONLINE_LIST, LOGIN, LOGIN_CHAT, CHANGE_PASSWORD

}
